let constants = {
  SUPPORTED_QUERY_DATE_FORMAT : "YYYY-MM-DD",
  SUPPORTED_QUERY_DATETIME_FORMAT : "YYYY-MM-DD HH:mm:ss",
  DATA_PROCESSING_TIMEOUT : 600000,
  BASE_URL : "/",
  RECORD_EXSISTS_ERROR_CODE : "23505",
  ZERO : 0,
  FETCH_PROCESS_DATA_TIME : 500,
  MIN_PASSWORD_LENGTH : 8,
  SESSION_SECRET_KEY : "12#42ddaghn**7",
  ONE : 1
};

module.exports = constants;